# Generated by Django 2.0.5 on 2018-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.TextField(help_text='Enter Article Title')),
                ('article_slug', models.TextField(default='', help_text='Enter Article Slug Here')),
                ('pubdate', models.DateField(auto_now=True)),
                ('metadata_article', models.DateField(auto_now=True)),
                ('text', models.TextField(default='la la la', help_text='Article Text Goes Here')),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Published')], default='d', help_text='Publication Status', max_length=1)),
            ],
            options={
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('rank', models.CharField(blank=True, choices=[('con', 'Contributing Writer'), ('ssw', 'Senior Staff Writer'), ('stw', 'Staff Writer')], default='con', help_text='Author Rank', max_length=3)),
                ('year', models.CharField(blank=True, choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('ju', 'Junior'), ('se', 'Senior'), ('gs', 'Graduate Student')], default='', help_text='Author Year', max_length=2)),
                ('articles', models.ManyToManyField(help_text='Select Articles Names', to='newspaper.Article')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_value', models.CharField(max_length=1000)),
                ('number_of_contents_with_tag', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(help_text='Select Author Names', to='newspaper.Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(help_text='Article Sections', to='newspaper.Sections'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(help_text='Tags for this Article', to='newspaper.Tags'),
        ),
    ]
