# Generated by Django 2.1.dev20180415210700 on 2018-04-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20180415_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='articles',
        ),
    ]
