# Generated by Django 2.0.5 on 2018-07-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_remove_author_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Section Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_value', models.CharField(max_length=1000)),
                ('number_of_contents_with_tag', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.CharField(blank=True, choices=[('fr', 'Freshman'), ('so', 'Sophomore'), ('ju', 'Junior'), ('se', 'Senior'), ('gs', 'Graduate Student')], default='', help_text='Author Year', max_length=2),
        ),
        migrations.AddField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(help_text='Article Sections', to='newspaper.Sections'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(help_text='Tags for this Article', to='newspaper.Tags'),
        ),
    ]
